pub mod jewels_and_stones;
pub mod unique_email_address;
pub mod find_anagram_mappings;
pub mod to_lower_case;
pub mod squares_of_a_sorted_array;
pub mod unique_morse_code_words;
pub mod n_repeated_element_in_size_2n_array;
pub mod sort_array_by_parity;
pub mod flipping_an_image;
